// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, BuckleScript and Reason!");

function add(x, y) {
  return x + y | 0;
}

function sum(item) {
  if (item) {
    return (item[0] + sum(item[1]) | 0) + sum(item[2]) | 0;
  } else {
    return 0;
  }
}

var myTree = /* Node */[
  1,
  /* Node */[
    2,
    /* Node */[
      4,
      /* Leaf */0,
      /* Leaf */0
    ],
    /* Node */[
      6,
      /* Leaf */0,
      /* Leaf */0
    ]
  ],
  /* Node */[
    3,
    /* Node */[
      5,
      /* Leaf */0,
      /* Leaf */0
    ],
    /* Node */[
      7,
      /* Leaf */0,
      /* Leaf */0
    ]
  ]
];

console.log(sum(myTree));

console.log("keyi");

var t = 14;

exports.add = add;
exports.t = t;
exports.sum = sum;
exports.myTree = myTree;
/*  Not a pure module */
