// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");

function last(_list) {
  while(true) {
    var list = _list;
    if (list) {
      var xs = list[1];
      if (xs) {
        _list = xs;
        continue ;
      } else {
        return Caml_option.some(list[0]);
      }
    } else {
      return ;
    }
  };
}

console.log(last(/* :: */[
          "12",
          /* [] */0
        ]));

exports.last = last;
/*  Not a pure module */
