// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

var divide = Caml_int32.div;

console.log(3);

exports.divide = divide;
/*  Not a pure module */
