// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

console.log(Pervasives.$at(/* :: */[
          5,
          /* :: */[
            1,
            /* [] */0
          ]
        ], /* :: */[
          8,
          /* :: */[
            4,
            /* [] */0
          ]
        ]));

console.log(List.append(/* :: */[
          5,
          /* :: */[
            1,
            /* [] */0
          ]
        ], /* :: */[
          8,
          /* :: */[
            4,
            /* [] */0
          ]
        ]));

/*  Not a pure module */
