// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function length(lst) {
  if (lst) {
    return 1 + length(lst[1]) | 0;
  } else {
    return 0;
  }
}

exports.length = length;
/* No side effect */
