// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function whatNumberAmIThinking(myNumber) {
  if (myNumber !== undefined) {
    return "My number is:" + String(myNumber);
  } else {
    return "I'm not thinking of any number";
  }
}

console.log(whatNumberAmIThinking(12));

exports.whatNumberAmIThinking = whatNumberAmIThinking;
/*  Not a pure module */
