// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function isSuperman(x) {
  if (x === "Clark Kent") {
    return true;
  } else {
    return false;
  }
}

exports.isSuperman = isSuperman;
/* No side effect */
