// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function addEveryNumberUpTo(x) {
  if (x < 0) {
    throw [
          Caml_builtin_exceptions.assert_failure,
          /* tuple */[
            "simpleRecursion.re",
            2,
            2
          ]
        ];
  }
  if (x !== 0) {
    return x + addEveryNumberUpTo(x - 1 | 0) | 0;
  } else {
    return 0;
  }
}

exports.addEveryNumberUpTo = addEveryNumberUpTo;
/* No side effect */
