// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var ListIntro$Reason = require("./ListIntro.bs.js");

console.log(ListIntro$Reason.length(/* :: */[
          "12",
          /* [] */0
        ]));

/*  Not a pure module */
