// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function add1(arg) {
  return arg + 1;
}

function add2(arg) {
  return arg + 1 | 0;
}

function stringAppend(x, y) {
  return x + y;
}

function square(x) {
  return Caml_int32.imul(x, x);
}

function half(x) {
  return x / 2 | 0;
}

function add(x, y) {
  return x + y | 0;
}

console.log("(5^2)/2=" + String(12));

var halved = 12;

var toString = String(halved);

console.log("(5^2)/2 = " + toString);

exports.add1 = add1;
exports.add2 = add2;
exports.stringAppend = stringAppend;
exports.square = square;
exports.half = half;
exports.add = add;
/*  Not a pure module */
