// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

var fristName = "Fred";

var lastName = "Flintstone";

var fullName = "FredFlintstone";

throw [
      Caml_builtin_exceptions.assert_failure,
      /* tuple */[
        "type.re",
        17,
        0
      ]
    ];

exports.four = four;
exports.floatfour = floatfour;
exports.fristName = fristName;
exports.lastName = lastName;
exports.fullName = fullName;
exports.aBooleanFalse = aBooleanFalse;
/*  Not a pure module */
