[package]
name = "learn-cargo"
version = "0.1.0"
authors = ["ben <544652471@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
